
name: face-recognition-api

networks:
  face-infra:
    external: true

services:
  api:
    build: .
    networks:
      - face-infra  
    environment:
      DATABASE_URL: "Server=infra-sqlserver,1433;Database=facerecog;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True"
      REDIS_URL: redis://:changeme@infra-redis:6379
      RABBITMQ_URL: amqp://appuser:changeme@infra-rabbitmq:5672
    depends_on:
      {}
