## RabbitMQ Configuration
log.console = true
log.console.level = warning

# Limit memory usage to no more than 40% of the container limit.
vm_memory_high_watermark.relative = 0.4
disk_free_limit.absolute = 1GB
